blank_issues_enabled: true
contact_links:
  - name: Winget Client issues
    url: https://github.com/microsoft/winget-cli/issues
    about: Please create issues related to the winget client here.
  - name: General Question
    url: https://github.com/microsoft/winget-pkgs/discussions/new
    about: Have a question on something? Start a new discussion thread.
  - name: Review open issues
    url: https://github.com/microsoft/winget-pkgs/issues
    about: Please check if your issue isn't already there.
